<?php

namespace AppBundle\Repository;

/**
 * artistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class artistaRepository extends \Doctrine\ORM\EntityRepository
{
}
