<?php

namespace AppBundle\Repository;

/**
 * tipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipoRepository extends \Doctrine\ORM\EntityRepository
{
}
